import Nav from "./components/Nav"
import Footer from "./components/Footer"
import { ClerkProvider, SignedIn, SignedOut, SignIn } from '@clerk/nextjs/app-beta';
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">

      <body >
<SignIn></SignIn>
  <Nav />
        {children}
        <Footer />
 
 
      


    
        </body>
    </html>
    </ClerkProvider>
  )
}
